apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: p2
  ports:
  - protocol: TCP
    port: 80  # Exposed port
    targetPort: 8090  # Port your application listens on
  type: LoadBalancer  # Expose service externally
