apiVersion: v1
kind: Service
metadata:
  name: p2-service
spec:
  type: NodePort
  selector:
    app: p2
  ports:
    - port: 8090
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
spec:
  selector:
    matchLabels:
      app: p2
  replicas: 1
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
        - name: p2
          image: cebrailkaya/p2:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/swe304"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "963258741"