apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
  labels:
    app: p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
        - name: p2
          image: cebrailkaya/p2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/swe304"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "963258741"
---
apiVersion: v1
kind: Service
metadata:
  name: p2-service
spec:
  selector:
    app: p2
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
